[book]
authors = ["cornmonger"]
language = "en"
multilingual = false
src = "src"
title = "cornmonger's site"
description = "cornmonger's personal website"

[output.html]
default-theme="coal"
preferred-dark-theme="coal"
no-section-label=true
